# Generated by Django 5.0.3 on 2024-04-04 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта клиента')),
                ('comment', models.CharField(blank=True, max_length=300, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тема сообщения')),
                ('message', models.CharField(max_length=400, verbose_name='Тело сообщения')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название рассылки')),
                ('time_start', models.DateTimeField(verbose_name='Дата и время первой отправки рассылки')),
                ('period', models.CharField(choices=[('1', 'раз в день'), ('7', 'раз в неделю'), ('30', 'раз в месяц')], default='1', max_length=20, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('created', 'создана'), ('run', 'запущена'), ('done', 'завершена')], default='created', max_length=20, verbose_name='Статус')),
                ('client', models.ManyToManyField(to='mailing.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время последней попытки')),
                ('status', models.CharField(choices=[('success', 'успешно'), ('fail', 'не успешно')], default='success', max_length=50, verbose_name='Статус')),
                ('response', models.CharField(blank=True, max_length=300, null=True, verbose_name='ответ сервера')),
                ('mailing_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки',
            },
        ),
    ]
