# Generated by Django 5.0.3 on 2024-04-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_mailing_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания рассылки '),
        ),
    ]
