# Generated by Django 5.0.3 on 2024-04-17 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_client_owner_mailing_owner_message_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_deactivate_mailing ', 'can deactivate mailing')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
